Change the base dir and add suggesting using Pebbledb
ronin-chain/ronin-documentation pull request #37
Opened 2024-10-06 15:23 UTC by huyngopt1994

2024-10-08 07:41 UTC, minh-bq commented
Why do we need to change the base directory?

2024-10-08 10:20 UTC, huyngopt1994 commented
@minh-bq https://github.com/ronin-chain/ronin-documentation/commit/51a86373c6e6e866c1f698844450ad895031d154#diff-6f2bbbd7a44fdbc7e2073d48a3efcf1cb48e9ddc72955bd77b11762dcda32aa1 Seem @RodinGolodin updated the in step 1 for creating sub directory docker but missing for updating in 5th step which leads this error

2024-10-08 10:26 UTC, RodinGolodin commented
> @minh-bq [51a8637#diff-6f2bbbd7a44fdbc7e2073d48a3efcf1cb48e9ddc72955bd77b11762dcda32aa1](https://github.com/ronin-chain/ronin-documentation/commit/51a86373c6e6e866c1f698844450ad895031d154#diff-6f2bbbd7a44fdbc7e2073d48a3efcf1cb48e9ddc72955bd77b11762dcda32aa1) Seem @RodinGolodin updated the in step 1 for creating sub directory docker but missing for updating in 5th step which leads this error

Possibly I did miss the update. Thanks for raising this @huyngopt1994 !

2024-10-08 11:10 UTC, minh-bq approved these changes

2024-10-09 02:57 UTC, RodinGolodin requested changes

2024-10-09 02:57 UTC, RodinGolodin commented on docs/validators/setup/mainnet/run-combined.md
> +5. (Optional) Download the snapshot from the [ronin-snapshot](https://github.com/axieinfinity/ronin-snapshot) repo (Prefer using Pebbledb):
@huyngopt1994 Let's rewrite a bit to remove the parentheses:
(Optional) Download the snapshot from the [ronin-snapshot](https://github.com/axieinfinity/ronin-snapshot) repo, preferably using PebbleDB:

2024-10-09 02:57 UTC, RodinGolodin commented on docs/validators/setup/mainnet/run-non-validator.md
> +4. (Optional) Download the snapshot from the [ronin-snapshot](https://github.com/axieinfinity/ronin-snapshot) repo (Prefer using Pebbledb):
(Optional) Download the snapshot from the [ronin-snapshot](https://github.com/axieinfinity/ronin-snapshot) repo, preferably using PebbleDB:

2024-10-09 02:57 UTC, RodinGolodin commented on docs/validators/setup/mainnet/run-validator.md
> +4. (Optional) Download the snapshot from the [ronin-snapshot](https://github.com/axieinfinity/ronin-snapshot) repo (Prefer using Pebbledb):
(Optional) Download the snapshot from the [ronin-snapshot](https://github.com/axieinfinity/ronin-snapshot) repo, preferably using PebbleDB:

2024-10-09 04:54 UTC, huyngopt1994 commented
@RodinGolodin updated

2024-10-09 09:25 UTC, RodinGolodin approved these changes

2024-10-09 09:25 UTC, merged